### ISSUE TITLE
NFS Support?

### ISSUE THREAD

**Issue by gaika** [ericpruitt/sshfsexec#3]
Is it possible to support NFS the same way, or maybe through a config file?

**Comment by ericpruitt** [comment]
Are you using sshfsexec on macOS or Linux?

**Comment by gaika** [comment]
Linux

**Comment by ericpruitt** [comment]
There's no way to do this currently. If you're comfortable writing code in Python, you could modify the "sshfsmountmap" just before the "return" statement with some like `mapping.update({ ... })` with a hard-coded dictionary in the same format as the dictionary used for the SSH mounts. For example:

```
mapping.update({
    '/home/gaika/mounts/nfs-example.com-home-directory': ('gaika@example.com', '/home/gaika')
})
```

I'll setup an NFS mount on one of my machines later to see how difficult it would be to implement in a configurable manner and get back to you in a few days.

**Comment by gaika** [comment]
If it is just `mapping` then it should be easy to extend, like it is done in  https://github.com/ericpruitt/sshfsexec/blob/master/sshfsexec.py#L75-L78 only for nfs type.

**Comment by ericpruitt** [comment]
Yes, I know what part of the code needs to be changed; I wrote the tool after all, and those lines are literally right above the ones I suggested you could edit. The problem is that I don't use NFS, so I don't have any NFS entries in my mount configuration to implement and test the changes.

**Comment by gaika** [comment]
I'll implement and submit a PR, was just checking if that's the right place to make changes. Thanks!

**Comment by ericpruitt** [comment]
That sounds good to me. In that case, I'll hold off adding code to make it possible to edit the mount map from the configuration file to avoid a merge conflict. Minor note -- don't worry about extracting the device identifier for the NFS mount since the "device" variable in that function isn't even used. Looking over the commit history, I forgot to remove it in d00b11bf5ad926f96db19ef27a30deb443ae79c7 after I stopped using it in one of the earlier implementations of the mapping dictionary.

**Comment by gaika** [comment]
Now only need the docs

**Comment by ericpruitt** [comment]
Documentation added in https://github.com/ericpruitt/sshfsexec/commit/1fb62ef9ed6a050ec013f314fcb588654eaa4509.
